name: Towards Liveaboard
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cf460188-5862-4869-acb2-38db5b05100f.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8f4cfda-f80a-4c5d-874a-1dcf7eaf9dfd.jpg
layout_spectrum: 0.4932472224435815
typography_spectrum: 0.19966821573812993
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.09717747148061816
  lightness: 0.22574648814128326
  saturation: 0.365142683034191
  rhythmicContrast: 0.04229401343321373
title: Towards Liveaboard
description: 'The dream to live on a sailboat, and the journey to get there'
content:
  - id: 8fc002f0-db0e-4840-a204-52a567884ff5
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/128058d2-2942-47d7-b397-5093b7f220ea.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/128058d2-2942-47d7-b397-5093b7f220ea.png
    metadata: {}
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: 0d3308fa-2d4f-4444-a022-19b8abd8775f
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/fafa7a500ae6e6dc26467f306183efad30c37ad7.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/fafa7a500ae6e6dc26467f306183efad30c37ad7.jpg
    metadata: {}
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
navigation:
  - name: About Us
    id: b2c6cb02-1cec-4de7-9b14-12538dbd3fc0
    type: content
github: true
