name: Towards Liveaboard
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cf460188-5862-4869-acb2-38db5b05100f.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8f4cfda-f80a-4c5d-874a-1dcf7eaf9dfd.jpg
layout_spectrum: 0.4932472224435815
typography_spectrum: 0.19966821573812993
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.09717747148061816
  lightness: 0.22574648814128326
  saturation: 0.365142683034191
  rhythmicContrast: 0.041294013433213726
title: Towards Liveaboard
description: 'The dream to live on a sailboat, and the journey to get there'
content:
- id: '8fc002f0-db0e-4840-a204-52a567884ff5'
  type: 'image'
  src: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/128058d2-2942-47d7-b397-5093b7f220ea.png'
  html: '<img src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/128058d2-2942-47d7-b397-5093b7f220ea.png">'
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
navigation:
  - name: About Us
    id: b2c6cb02-1cec-4de7-9b14-12538dbd3fc0
    type: content
github: true
